//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAptitudeTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Candidate_Test_Detail = new HashSet<Candidate_Test_Detail>();
            this.Scores = new HashSet<Score>();
            this.TestCandidateLists = new HashSet<TestCandidateList>();
        }
    
        public int CandidateID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public string Education_Details { get; set; }
        public string Work_Experience { get; set; }
        public Nullable<int> TestCode { get; set; }
        public Nullable<int> TestStatus { get; set; }
        public Nullable<int> Pass { get; set; }
        public Nullable<double> FinalScore { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate_Test_Detail> Candidate_Test_Detail { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCandidateList> TestCandidateLists { get; set; }
    }
}
